### ISSUE TITLE
HTTP request response spec for event store

### ISSUE THREAD

**Issue by normanjaeckel** [FinnStutzenstein/os4-notes#3]
Can I get a spec for the HTTP request payload and the responses when reading data from event store?

What will be the default port for the service? (I know that this is only relevant during development if one develops/tests without docker). Action backend may listen on 8000, ok? @ostcar?

**Comment by ostcar** [comment]
This should be done

**Comment by ostcar** [comment]
@FinnStutzenstein I can't remove this issue from my list of issues, where I am mentioned. Would it be possible for you to close this issue?
